---
title: "challenge2"
format: html
---

z <- read.csv("https://raw.githubusercontent.com/difiore/ada-datasets/main/zombies.csv")

#Calculate the population mean and standard deviation for each quantitative random variable in the dataset (height, weight, age, number of zombies killed, and years of education).

population_stats <- z %>%
  summarise(
    height_popMean = mean(height, na.rm = TRUE),
    height_SD = sqrt(sum((height - mean(height, na.rm = TRUE))^2)/length(height)),
    weight_popMean = mean(weight, na.rm = TRUE),
    weight_SD = sqrt(sum((weight - mean(weight, na.rm = TRUE))^2)/length(weight)),
    age_popMean = mean(age, na.rm = TRUE),
    age_SD = sqrt(sum((age - mean(age, na.rm = TRUE))^2)/length(age)),
    zombiesKilled_popMean = mean(zombies_killed, na.rm = TRUE),
    zombiesKilled_SD = sqrt(sum((zombies_killed - mean(zombies_killed, na.rm = TRUE))^2)/length(zombies_killed)),
    edu_popMean = mean(years_of_education, na.rm = TRUE),
    edu_SD = sqrt(sum((years_of_education - mean(years_of_education, na.rm = TRUE))^2)/length(years_of_education)))
population_stats

#Use {ggplot} and make boxplots of each of these variables by gender.

quant_variables <- z %>%
  pivot_longer(
    cols = c(height, weight, age, zombies_killed, years_of_education),
    names_to = "variable", 
    values_to = "value"
  )
quant_variables

ggplot(data = quant_variables, aes(x = gender, y = value,  fill = gender)) + 
geom_boxplot() + facet_wrap(~ variable, scales = "free_y")

#Use {ggplot} and make scatterplots of height and weight in relation to age (i.e., use age as the  variable), using different colored points for males versus females. Do these variables seem to be related? In what way?
#Answer: Age seems to be positive correlated with height for both genders. There does not seem to be a correlation between age and weight for either gender. 

ggplot(z, aes(x = age, y = height, color = gender)) + geom_point()
ggplot(z, aes(x = age, y = weight, color = gender)) + geom_point()

#Using histograms and Q-Q plots, check whether each of the quantitative variables seem to be drawn from a normal distribution. Which seem to be and which do not?
#Answer: Age, height, weight seem to be following a normal distribution. Number of zombies killed does not. 

ggplot(quant_variables, aes(x = value)) + geom_histogram() + facet_wrap(~ variable, scales = "free")
ggqqplot(quant_variables, x = "value", facet.by = "variable")

#Now use the sample_n() or slice_sample() function from {dplyr} to sample ONE subset of 50 zombie apocalypse survivors (without replacement) from this population and calculate the mean and sample standard deviation for each variable. Also estimate the standard error for each variable based on this one sample and use that to construct a theoretical 95% confidence interval for each mean. You can use either the standard normal or a Student’s t distribution to derive the critical values needed to calculate the lower and upper limits of the CI.

sampleZombies <- z %>% 
  sample_n(size = 50) %>% 
  summarise(
    height_mean = mean(height, na.rm = TRUE),
    height_SD = sqrt(sum((height - mean(height, na.rm = TRUE))^2)/length(height)),
    height_SE = height_SD/sqrt(50),
    weight_mean = mean(weight, na.rm = TRUE),
    weight_SD = sqrt(sum((weight - mean(weight, na.rm = TRUE))^2)/length(weight)),
    weight_SE = weight_SD/sqrt(50),
    age_mean = mean(age, na.rm = TRUE),
    age_SD = sqrt(sum((age - mean(age, na.rm = TRUE))^2)/length(age)),
    age_SE = age_SD/sqrt(50),
    zombiesKilled_mean = mean(zombies_killed, na.rm = TRUE),
    zombiesKilled_SD = sqrt(sum((zombies_killed - mean(zombies_killed, na.rm = TRUE))^2)/length(zombies_killed)),
    zombiesKilled_SE = zombiesKilled_SD/sqrt(50),
    edu_mean = mean(years_of_education, na.rm = TRUE),
    edu_SD = sqrt(sum((years_of_education - mean(years_of_education, na.rm = TRUE))^2)/length(years_of_education)),
    edu_SE = edu_SD/sqrt(50))

t_crit <- qt(0.975, df = 50 - 1)

height_lower <- sampleZombies$height_mean - t_crit * sampleZombies$height_SE
height_upper <- sampleZombies$height_mean + t_crit * sampleZombies$height_SE

weight_lower <- sampleZombies$weight_mean - t_crit * sampleZombies$weight_SE
weight_upper <- sampleZombies$weight_mean + t_crit * sampleZombies$weight_SE

age_lower <- sampleZombies$age_mean - t_crit * sampleZombies$age_SE
age_upper <- sampleZombies$age_mean + t_crit * sampleZombies$age_SE

zombiesKilled_lower <- sampleZombies$zombiesKilled_mean - t_crit * sampleZombies$zombiesKilled_SE
zombiesKilled_upper <- sampleZombies$zombiesKilled_mean + t_crit * sampleZombies$zombiesKilled_SE

edu_lower <- sampleZombies$edu_mean - t_crit * sampleZombies$edu_SE
edu_upper <- sampleZombies$edu_mean + t_crit * sampleZombies$edu_SE

#Then draw another 199 random samples of 50 zombie apocalypse survivors out of the population and calculate the mean for each of the these samples. Together with the first sample you drew out, you now have a set of 200 means for each variable (each of which is based on 50 observations), which constitutes a sampling distribution for each variable. What are the means and standard deviations of the sampling distribution for each variable? How do the standard deviations of the sampling distribution for each variable compare to the standard errors estimated from your first sample of size 50?

zombie_sample_distribution <- z %>% 
  rep_sample_n(size = 50, reps = 199) %>%
  summarise(
    height_mean = mean(height, na.rm = TRUE),
    weight_mean = mean(weight, na.rm = TRUE),
    age_mean = mean(age, na.rm = TRUE),
    zombiesKilled_mean = mean(zombies_killed, na.rm = TRUE),
    edu_mean = mean(years_of_education, na.rm = TRUE)
  )
zombie_sample_distribution

#Plot the sampling distributions for each variable mean. What do they look like? Are they normally distributed? What about for those variables that you concluded were not originally drawn from a normal distribution?

zombie_sample_distribution_grouped <- zombie_sample_distribution %>%
  pivot_longer(
    cols = c(height_mean, weight_mean, age_mean, zombiesKilled_mean, edu_mean),
    names_to = "variable", 
    values_to = "value"
  )
zombie_sample_distribution_grouped

ggplot(zombie_sample_distribution_grouped, aes(x = value)) + geom_histogram() + facet_wrap(~ variable, scales = "free")

#Construct a 95% confidence interval for each mean directly from the sampling distribution of sample means using the central 95% that distribution (i.e., by setting the lower and upper CI bounds to 2.5% and 97.5% of the way through that distribution).

CIs <- zombie_sample_distribution %>%
 summarise(
    height_CI <- quantile(height_mean, probs = c(0.025, 0.975)),
    weight_CI <- quantile(weight_mean, probs = c(0.025, 0.975)),
    age_CI <- quantile(age_mean, probs = c(0.025, 0.975)),
    zombies_CI <- quantile(zombiesKilled_mean, probs = c(0.025, 0.975)),
    edu_CI <- quantile(edu_mean, probs = c(0.025, 0.975))
  )
CIs

#Finally, use bootstrapping to generate a 95% confidence interval for each variable mean by resampling 1000 samples, with replacement, from your original sample (i.e., by setting the lower and upper CI bounds to 2.5% and 97.5% of the way through the sampling distribution generated by bootstrapping). How does this compare to the CIs generated in Step 9?

