---
title: "assignment"
format: html
---
library(tidyverse)
library(dplyr)
library(ggplot2)
library(infer)
library(ggpubr)
 
d <- read.csv("https://raw.githubusercontent.com/difiore/ada-datasets/main/IMDB-movies.csv")

#Use a one-line statement to filter the dataset to include just movies from 1920 to 1979 and movies that are between 1 and 3 hours long (runtimeMinutes >= 60 and runtimeMinutes <= 180), and add a new column that codes the startYear into a new variable, decade (“20s”, “30s”, …“70s”). If you do this correctly, there should be 5651 movies remaining in the dataset.

filtered_data <- d %>%
  filter(startYear >= 1920 & startYear <= 1979) %>%
  filter(runtimeMinutes >= 60 & runtimeMinutes <= 180) %>%
  mutate(
  decade = paste0(substr(startYear, start = 3, stop = 3), "0s")
  )
dim(filtered_data)
filtered_data

#Use {ggplot2} (which is part of {tidyverse}) to plot histograms of the distribution of runtimeMinutes for each decade.

ggplot(data = filtered_data, aes(x = runtimeMinutes)) + geom_histogram() + 
facet_wrap(~ decade, scales = "free_y")

#Use a one-line statement to calculate the population mean and population standard deviation in runtimeMinutes for each decade and save the results in a new dataframe called results.

results <- filtered_data %>%
  group_by(decade) %>%
  summarise(
  populationMean = mean(runtimeMinutes, na.rm = TRUE), 
  populationSD = sd(runtimeMinutes, na.rm = TRUE)
  )
results

#Draw a single sample of 100 movies, without replacement, from each decade and calculate the single sample mean and single sample standard deviation in runtimeMinutes for each decades. Recall that your single sample mean for each decade is an estimate of the population mean for each decade.

singleSample <- filtered_data %>% 
  group_by(decade) %>% 
  sample_n(size = 100) %>% 
  summarise(
    sampleMean = mean(runtimeMinutes, na.rm = TRUE),
    sampleSD = sd(runtimeMinutes, na.rm = TRUE), 
  )
singleSample

#Calculate for each decade the standard error around your estimate of the population mean runtimeMinutes based on the standard deviation and sample size (n=100 movies) of your single sample.

singleSample <- singleSample %>%
mutate(SE = sampleSD/sqrt(100))
singleSample

#Compare these estimates to the actual population mean runtimeMinutes for each decade and to the expected SE in the population mean for samples of size 100 based on the known population standard deviation for each decade.

filtered_data %>% 
  group_by(decade) %>%
  summarise(
    populationMean = mean(runtimeMinutes, na.rm = TRUE),
    populationSD = sd(runtimeMinutes, na.rm = TRUE), 
    expectedSE = populationSD/sqrt(100)
  ) 

#Generate a sampling distribution of mean runtimeMinutes for each decade by [a] drawing 1000 random samples of 100 movies from each decade, without replacement, and, for each sample, [b] calculating the mean runtimeMinutes and the standard deviation in runtimeMinutes for each decade. Use either a standard for( ){ } loop, the do(reps) * formulation from {mosaic}, the rerun() function from {purrr}, or the rep_sample_n() workflow from {infer} to generate your these sampling distributions (see Module 16).

samplingDist <- filtered_data %>% 
  rep_sample_n(size = 100, reps = 1000) %>%
  group_by(decade, replicate) %>%
  summarise(
    sampleMean = mean(runtimeMinutes, na.rm = TRUE),
    sampleSD = sd(runtimeMinutes, na.rm = TRUE)
  )

#Then, calculate the mean and the standard deviation of the sampling distribution of sample means for each decade (the former should be a very good estimate of the population mean, while the latter is another estimate of the standard error in our estimate of the population mean for a particular sample size) and plot a histogram of the sampling distribution for each decade. What shape does it have?

samplingDist %>%
  summarise(
    meanOfMeans = mean(sampleMean, na.rm = TRUE),
    SDofMeans = sd(sampleMean, na.rm = TRUE)
  ) %>%

ggplot(data = samplingDist, aes(x = sampleMean)) + geom_histogram() + facet_wrap(~ decade)

#Finally, compare the standard error in runtimeMinutes for samples of size 100 from each decade [1] as estimated from your first sample of 100 movies, [2] as calculated from the known population standard deviations for each decade, and [3] as estimated from the sampling distribution of sample means for each decade.

  
z <- read.csv("https://raw.githubusercontent.com/difiore/ada-datasets/main/zombies.csv")

#Calculate the population mean and standard deviation for each quantitative random variable in the dataset (height, weight, age, number of zombies killed, and years of education).

population_stats <- z %>%
  summarise(
    height_popMean = mean(height, na.rm = TRUE),
    height_SD = sqrt(sum((height - mean(height, na.rm = TRUE))^2)/length(height)),
    weight_popMean = mean(weight, na.rm = TRUE),
    weight_SD = sqrt(sum((weight - mean(weight, na.rm = TRUE))^2)/length(weight)),
    age_popMean = mean(age, na.rm = TRUE),
    age_SD = sqrt(sum((age - mean(age, na.rm = TRUE))^2)/length(age)),
    zombiesKilled_popMean = mean(zombies_killed, na.rm = TRUE),
    zombiesKilled_SD = sqrt(sum((zombies_killed - mean(zombies_killed, na.rm = TRUE))^2)/length(zombies_killed)),
    edu_popMean = mean(years_of_education, na.rm = TRUE),
    edu_SD = sqrt(sum((years_of_education - mean(years_of_education, na.rm = TRUE))^2)/length(years_of_education)))
population_stats

#Use {ggplot} and make boxplots of each of these variables by gender.

quant_variables <- z %>%
  pivot_longer(
    cols = c(height, weight, age, zombies_killed, years_of_education),
    names_to = "variable", 
    values_to = "value"
  )
quant_variables

ggplot(data = quant_variables, aes(x = gender, y = value,  fill = gender)) + 
geom_boxplot() + facet_wrap(~ variable, scales = "free_y")

#Use {ggplot} and make scatterplots of height and weight in relation to age (i.e., use age as the  variable), using different colored points for males versus females. Do these variables seem to be related? In what way?
#Answer: Age seems to be positive correlated with height for both genders. There does not seem to be a correlation between age and weight for either gender. 

ggplot(z, aes(x = age, y = height, color = gender)) + geom_point()
ggplot(z, aes(x = age, y = weight, color = gender)) + geom_point()

#Using histograms and Q-Q plots, check whether each of the quantitative variables seem to be drawn from a normal distribution. Which seem to be and which do not?
#Answer: Age, height, weight seem to be following a normal distribution. Number of zombies killed does not. 

ggplot(quant_variables, aes(x = value)) + geom_histogram() + facet_wrap(~ variable, scales = "free")
ggqqplot(quant_variables, x = "value", facet.by = "variable")

#Now use the sample_n() or slice_sample() function from {dplyr} to sample ONE subset of 50 zombie apocalypse survivors (without replacement) from this population and calculate the mean and sample standard deviation for each variable. Also estimate the standard error for each variable based on this one sample and use that to construct a theoretical 95% confidence interval for each mean. You can use either the standard normal or a Student’s t distribution to derive the critical values needed to calculate the lower and upper limits of the CI.

sampleZombies <- z %>% 
  sample_n(size = 50) %>% 
  summarise(
    height_mean = mean(height, na.rm = TRUE),
    height_SD = sqrt(sum((height - mean(height, na.rm = TRUE))^2)/length(height)),
    height_SE = height_SD/sqrt(50),
    weight_mean = mean(weight, na.rm = TRUE),
    weight_SD = sqrt(sum((weight - mean(weight, na.rm = TRUE))^2)/length(weight)),
    weight_SE = weight_SD/sqrt(50),
    age_mean = mean(age, na.rm = TRUE),
    age_SD = sqrt(sum((age - mean(age, na.rm = TRUE))^2)/length(age)),
    age_SE = age_SD/sqrt(50),
    zombiesKilled_mean = mean(zombies_killed, na.rm = TRUE),
    zombiesKilled_SD = sqrt(sum((zombies_killed - mean(zombies_killed, na.rm = TRUE))^2)/length(zombies_killed)),
    zombiesKilled_SE = zombiesKilled_SD/sqrt(50),
    edu_mean = mean(years_of_education, na.rm = TRUE),
    edu_SD = sqrt(sum((years_of_education - mean(years_of_education, na.rm = TRUE))^2)/length(years_of_education)),
    edu_SE = edu_SD/sqrt(50))

t_crit <- qt(0.975, df = 50 - 1)

height_lower <- sampleZombies$height_mean - t_crit * sampleZombies$height_SE
height_upper <- sampleZombies$height_mean + t_crit * sampleZombies$height_SE

weight_lower <- sampleZombies$weight_mean - t_crit * sampleZombies$weight_SE
weight_upper <- sampleZombies$weight_mean + t_crit * sampleZombies$weight_SE

age_lower <- sampleZombies$age_mean - t_crit * sampleZombies$age_SE
age_upper <- sampleZombies$age_mean + t_crit * sampleZombies$age_SE

zombiesKilled_lower <- sampleZombies$zombiesKilled_mean - t_crit * sampleZombies$zombiesKilled_SE
zombiesKilled_upper <- sampleZombies$zombiesKilled_mean + t_crit * sampleZombies$zombiesKilled_SE

edu_lower <- sampleZombies$edu_mean - t_crit * sampleZombies$edu_SE
edu_upper <- sampleZombies$edu_mean + t_crit * sampleZombies$edu_SE

#Then draw another 199 random samples of 50 zombie apocalypse survivors out of the population and calculate the mean for each of the these samples. Together with the first sample you drew out, you now have a set of 200 means for each variable (each of which is based on 50 observations), which constitutes a sampling distribution for each variable. What are the means and standard deviations of the sampling distribution for each variable? How do the standard deviations of the sampling distribution for each variable compare to the standard errors estimated from your first sample of size 50?

zombie_sample_distribution <- z %>% 
  rep_sample_n(size = 50, reps = 199) %>%
  summarise(
    height_mean = mean(height, na.rm = TRUE),
    weight_mean = mean(weight, na.rm = TRUE),
    age_mean = mean(age, na.rm = TRUE),
    zombiesKilled_mean = mean(zombies_killed, na.rm = TRUE),
    edu_mean = mean(years_of_education, na.rm = TRUE)
  )
zombie_sample_distribution

#Plot the sampling distributions for each variable mean. What do they look like? Are they normally distributed? What about for those variables that you concluded were not originally drawn from a normal distribution?

zombie_sample_distribution_grouped <- zombie_sample_distribution %>%
  pivot_longer(
    cols = c(height_mean, weight_mean, age_mean, zombiesKilled_mean, edu_mean),
    names_to = "variable", 
    values_to = "value"
  )
zombie_sample_distribution_grouped

ggplot(zombie_sample_distribution_grouped, aes(x = value)) + geom_histogram() + facet_wrap(~ variable, scales = "free")

#Construct a 95% confidence interval for each mean directly from the sampling distribution of sample means using the central 95% that distribution (i.e., by setting the lower and upper CI bounds to 2.5% and 97.5% of the way through that distribution).

CIs <- zombie_sample_distribution %>%
 summarise(
    height_CI <- quantile(height_mean, probs = c(0.025, 0.975)),
    weight_CI <- quantile(weight_mean, probs = c(0.025, 0.975)),
    age_CI <- quantile(age_mean, probs = c(0.025, 0.975)),
    zombies_CI <- quantile(zombiesKilled_mean, probs = c(0.025, 0.975)),
    edu_CI <- quantile(edu_mean, probs = c(0.025, 0.975))
  )
CIs

#Finally, use bootstrapping to generate a 95% confidence interval for each variable mean by resampling 1000 samples, with replacement, from your original sample (i.e., by setting the lower and upper CI bounds to 2.5% and 97.5% of the way through the sampling distribution generated by bootstrapping). How does this compare to the CIs generated in Step 9?

